"""配置导入导出工具 — JSON/文本格式导入导出、配置解析"""

from __future__ import annotations

import json
from typing import Optional


class ConfigIO:
    """配置导入导出"""

    @staticmethod
    def export_json(config: dict, hostname: str = "device") -> str:
        """导出为JSON格式"""
        return json.dumps(config, indent=2, ensure_ascii=False)

    @staticmethod
    def export_text(config_text: str, hostname: str = "device") -> str:
        """导出为文本格式"""
        header = f"!\n! Configuration for {hostname}\n! Generated by NetOps Fusion\n!\n\n"
        return header + config_text

    @staticmethod
    def import_json(json_str: str) -> dict:
        """从JSON导入配置"""
        try:
            return json.loads(json_str)
        except json.JSONDecodeError as e:
            return {"error": f"JSON解析失败: {e}"}

    @staticmethod
    def parse_config_text(config_text: str) -> dict:
        """解析配置文本为结构化数据"""
        sections = {}
        current_section = None
        current_interface = None

        for line in config_text.splitlines():
            line = line.strip()
            if not line or line.startswith("#") or line.startswith("!"):
                continue

            if line.startswith("sysname ") or line.startswith("hostname "):
                sections["hostname"] = line.split(None, 1)[1]
            elif line.startswith("vlan "):
                parts = line.split()
                if "vlans" not in sections:
                    sections["vlans"] = []
                if parts[1].isdigit():
                    sections["vlans"].append(int(parts[1]))
            elif line.startswith("interface "):
                current_interface = line.split(None, 1)[1]
                if "interfaces" not in sections:
                    sections["interfaces"] = []
                sections["interfaces"].append({"name": current_interface})
            elif line.startswith("ip route-static") or line.startswith("ip route"):
                if "static_routes" not in sections:
                    sections["static_routes"] = []
                sections["static_routes"].append(line)
            elif line.startswith("ospf "):
                sections["ospf"] = line
            elif line.startswith("bgp "):
                sections["bgp"] = line
            elif line.startswith("acl number "):
                if "acls" not in sections:
                    sections["acls"] = []
                sections["acls"].append(int(line.split()[-1]))

        return sections


config_io = ConfigIO()
